[package]
name = "bela-template"
version = "0.1.0"
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies.bela]
git = "https://github.com/l0calh05t/bela-rs.git"
branch = "next"
features = [ "midi" ]
